name: Deploy Portfolio to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Configure GitHub Pages to use this run
      - uses: actions/configure-pages@v3

      # 2. Upload the `client/` folder as the artifact to deploy
      - name: Upload client/ as Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'client'

      # 3. Publish to GitHub Pages
      - uses: actions/deploy-pages@v1
